### ISSUE TITLE
Erros loading a test file are swallowed by this reporter

### ISSUE THREAD

**Issue by alcuadrado** [voxpelli/node-test-pretty-reporter#16]
Hi! First of all, I really like this reporter. Thanks for building it.

I noticed there's one bug/limitation when there's an error when loading a file. The error just isn't displayed.

To reproduce it all you need to do is create an npm project, install this reporter, and create a file `test/test.js`:

```js
throw new Error("foo");
```

Then running `node:test` with this reporter will look like this:

```
$ node --test --test-reporter=@voxpelli/node-test-pretty-reporter  

ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 142.345917
```

While running it without the reporter does show the error:

```
$ node --test                                                      
/workspaces/npmprojects/npmproject-1/test/test.js:1
throw new Error("foo");
^

Error: foo
    at Object.<anonymous> (/workspaces/npmprojects/npmproject-1/test/test.js:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:12)
    at node:internal/main/run_main_module:30:49

Node.js v22.2.0
✖ test/test.js (22.139417ms)
  'test failed'

ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 34.348833

✖ failing tests:

test at test/test.js:1:1
✖ test/test.js (22.139417ms)
  'test failed'
```

**Comment by alcuadrado** [comment]
After playing a bit with that example and this reporter:

```js
module.exports = async function* customReporter(source) {
  for await (const event of source) {
    console.log(event);
  }
};
```

I found that the events of type `"test:stderr"` seem to be ignored.

**Comment by alcuadrado** [comment]
Same with `"test:stdout"`
